/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StableForgeFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aavePool"
      | "aerodromeFactory"
      | "aerodromeRouter"
      | "creator"
      | "deployBootstrapper"
      | "deployToken"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BootstrapperDeployed" | "TokenDeployed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "aavePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aerodromeFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aerodromeRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deployBootstrapper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aerodromeFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aerodromeRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployBootstrapper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace BootstrapperDeployedEvent {
  export type InputTuple = [bootstrapper: AddressLike];
  export type OutputTuple = [bootstrapper: string];
  export interface OutputObject {
    bootstrapper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDeployedEvent {
  export type InputTuple = [
    token: AddressLike,
    name: string,
    symbol: string,
    supply: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    name: string,
    symbol: string,
    supply: bigint
  ];
  export interface OutputObject {
    token: string;
    name: string;
    symbol: string;
    supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StableForgeFactory extends BaseContract {
  connect(runner?: ContractRunner | null): StableForgeFactory;
  waitForDeployment(): Promise<this>;

  interface: StableForgeFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aavePool: TypedContractMethod<[], [string], "view">;

  aerodromeFactory: TypedContractMethod<[], [string], "view">;

  aerodromeRouter: TypedContractMethod<[], [string], "view">;

  creator: TypedContractMethod<[], [string], "view">;

  deployBootstrapper: TypedContractMethod<[], [string], "nonpayable">;

  deployToken: TypedContractMethod<
    [name_: string, symbol_: string, supply_: BigNumberish],
    [string],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aerodromeFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aerodromeRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployBootstrapper"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "deployToken"
  ): TypedContractMethod<
    [name_: string, symbol_: string, supply_: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BootstrapperDeployed"
  ): TypedContractEvent<
    BootstrapperDeployedEvent.InputTuple,
    BootstrapperDeployedEvent.OutputTuple,
    BootstrapperDeployedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDeployed"
  ): TypedContractEvent<
    TokenDeployedEvent.InputTuple,
    TokenDeployedEvent.OutputTuple,
    TokenDeployedEvent.OutputObject
  >;

  filters: {
    "BootstrapperDeployed(address)": TypedContractEvent<
      BootstrapperDeployedEvent.InputTuple,
      BootstrapperDeployedEvent.OutputTuple,
      BootstrapperDeployedEvent.OutputObject
    >;
    BootstrapperDeployed: TypedContractEvent<
      BootstrapperDeployedEvent.InputTuple,
      BootstrapperDeployedEvent.OutputTuple,
      BootstrapperDeployedEvent.OutputObject
    >;

    "TokenDeployed(address,string,string,uint256)": TypedContractEvent<
      TokenDeployedEvent.InputTuple,
      TokenDeployedEvent.OutputTuple,
      TokenDeployedEvent.OutputObject
    >;
    TokenDeployed: TypedContractEvent<
      TokenDeployedEvent.InputTuple,
      TokenDeployedEvent.OutputTuple,
      TokenDeployedEvent.OutputObject
    >;
  };
}
